#under edit
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env: 
  REPOENV: REPOENV



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
   
 

    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        env: 
          REP: 123
        run: |
          source option 
          echo "RIPP=${REPO}" >> $GITHUB_ENV
          #echo "::set-env name=REP::$REPO"
          echo $RIPP
          echo ${{ secrets.ghtoken }} > token.txt
          gh auth login --with-token < token.txt
          git remote rm origin 
          #change GHACCOUNT to yessoft when u finish 
          gh repo create $GHACCOUNT/$REPO  --template=$TEMPLATE --confirm --$ACCESS
          echo repo is created 
          git remote rm origin 
          echo ${GH_USERNAME}
          git config --global user.name ${{github.actor}}
          git config --global user.email "yescloud@gmail.com"
          echo git config is done 
          sleep 15
          git clone  https://github.com/$GHACCOUNT/$REPO.git
          echo git clone is done
          cd $REPO/k8s
          echo cd is done 
          sed -i "s|FORREPLACE1235|$REPO|g" server.yaml
          echo sed 1 is done
          sed -i "s|FORREPLACE1235|$REPO|g" mysql.yaml
          echo sed 2 is done
          sed -i "s|FORREPLACE1235|$REPO|g" namespace.yaml
          echo sed 3 is done 
          
          echo string replace is done 
         
          git remote -v
          git remote rm origin 
          echo remote remove is done
          #git remote set-url origin git@github.com:@GHACCOUNT/$REPO.git
          git remote add origin https://aliomom:${{ secrets.ghtoken }}@github.com/aliomom/$REPO.git
          git add .
          git commit -a -m "iit"
          #git push --set-upstream origin symfony-app-skeleton

          git push origin HEAD:symfony-app-skeleton

      - uses: actions/checkout@v2
        with:
         repository: yes-soft-de/environment-tools
         token: ${{ secrets.ENVGHTOKEN }}
      - run: |
         echo the repo is 
         echo ${RIPP}
         mkdir -p ${RIPP} && cd ${RIPP}
         
         echo creating new directory is done
         ls -al
         echo "${{ secrets.ENV }}" > .env
         echo create .env
         echo "${{ secrets.HTACCESS }}" > .htaccess
         echo create .htaccess
         echo creating .env and .htaccess is done  
         
         mkdir jwt && cd jwt
         echo creating new jwt dir
         
         openssl genpkey -out private.pem -aes256 -pass pass:${{ secrets.PASS }} -algorithm rsa -pkeyopt rsa_keygen_bits:4096 
         openssl pkey -passin pass:${{ secrets.PASS }} -in private.pem -out public.pem -pubout
         echo creating new jwt 
         ls -al 
         cd .. && ls -al
         
         git add .
         git commit -a -m "add .env and .htacces and jwt"
         git push 
         
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          service_account_email: ${{ secrets.service_account_email }}
          project_id: ${{ secrets.GKE_PROJECT }}
          export_default_credentials: true

      - run: |-
          ls 
