# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls 
          source option 
          echo ${{ secrets.ghtoken }} > token.txt
          ls 
          gh auth login --with-token < token.txt
          git remote rm origin 
          
          git remote -v
          echo login is done
          gh repo create $GHACCOUNT/$REPO  --template=$TEMPLATE --confirm --$ACCESS
          git remote -v
          git config --global user.name "aliomom"
          git config --global user.email "a.omom11115@gmail.com"

          git add .
          git commit -m "First batch of files"
          git push --set-upstream origin main

          echo repo create from template is done 
          git clone  https://github.com/$GHACCOUNT/$REPO.git
          
          echo repo clone is done 
          cd $REPO
          ls -al 
          sed -i 's/ske/$REPO/g' web.yaml
          sed -i 's/ske/$REPO/g' mysql.yaml
          sed -i 's/ske/$REPO/g' namespace.yaml
          echo string replace is done 
          gh pr create
          echo push is done 
      # sudo apt update -q && sudo apt install git-all -y -q
      #sudo apt install software-properties-common -y 
      #sudo apt-get install dirmngr -y
      #sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key C99B11DEB97541F0
      #sudo apt-add-repository https://cli.github.com/packages 
      #sudo apt update -q
      #sudo apt install gh -y -q
      #sudo apt update -q 
      #sudo apt upgrade -q
         
      # echo now you are connected to github
          

